/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import collation from './collation'
import column from './column'
import engine from './engine'
import type_ from './type'

const database = {
  collation,
  column,
  engine,
  type: type_,
}

export default database
