/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import supplemental from './supplemental'
import words from './words'

const lorem = {
  supplemental,
  words,
}

export default lorem
