/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import month from './month'
import weekday from './weekday'

const date = {
  month,
  weekday,
}

export default date
