/*
 * This file is automatically generated.
 * Run 'pnpm run generate:locales' to update.
 */

import directoryPaths from './directoryPaths'
import mimeTypes from './mimeTypes'

const system = {
  directoryPaths,
  mimeTypes,
}

export default system
