import { TRANSFORMATIONS, NUM_CHECKS } from './testutils'

test('determinism', () => {
  const input = 'some-value'

  const check = (name: string) => {
    const value1 = TRANSFORMATIONS[name](input)

    let i = -1

    while (++i < NUM_CHECKS) {
      expect(TRANSFORMATIONS[name](input)).toEqual(value1)
    }
  }

  Object.keys(TRANSFORMATIONS).forEach(check)
})

test('generated values', () => {
  const count = 10
  const results = {}

  const addResults = (name: string) => {
    const valueResults: unknown[] = []

    let i = -1

    while (++i < count) {
      valueResults.push(TRANSFORMATIONS[name](i))
    }

    results[name] = valueResults
  }

  Object.keys(TRANSFORMATIONS).forEach(addResults)

  expect(results).toMatchInlineSnapshot(`
    Object {
      "bool": Array [
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        true,
        false,
        true,
      ],
      "char": Array [
        "B",
        "D",
        "S",
        "5",
        "2",
        "8",
        "l",
        "X",
        "8",
        "l",
      ],
      "city": Array [
        "Ashburn",
        "Caguas",
        "Erie",
        "Citrus Heights",
        "Meridian",
        "Laredo",
        "Downers Grove",
        "Galveston",
        "Rochester Hills",
        "Everett",
      ],
      "country": Array [
        "French Polynesia",
        "Solomon Islands",
        "United States Minor Outlying Islands",
        "Mozambique",
        "Saint Pierre and Miquelon",
        "Mali",
        "Philippines",
        "Mexico",
        "Heard Island and McDonald Islands",
        "Iran",
      ],
      "countryCode": Array [
        "GE",
        "SN",
        "VC",
        "MS",
        "RU",
        "MA",
        "PG",
        "MK",
        "HR",
        "IO",
      ],
      "dateString": Array [
        "1989-02-02T01:50:46.000Z",
        "2019-08-16T07:35:00.000Z",
        "1996-09-17T09:12:15.000Z",
        "2005-02-06T01:39:33.000Z",
        "1988-09-25T08:24:37.000Z",
        "1984-05-17T04:05:19.000Z",
        "2017-10-10T22:04:02.000Z",
        "2015-04-28T03:27:56.000Z",
        "2012-05-01T17:08:34.000Z",
        "2001-02-18T13:05:43.000Z",
      ],
      "digit": Array [
        "9",
        "9",
        "6",
        "5",
        "8",
        "4",
        "7",
        "5",
        "2",
        "1",
      ],
      "email": Array [
        "Daniela_Will21346@givingfence.biz",
        "Laurence.DuBuque93767@debug-wingman.us",
        "Madyson.Barton50272@plopopportunist.info",
        "Olen_Kunze587@miaow-interior.biz",
        "Ardith.Yundt85426@splay-sonnet.org",
        "Brisa_Miller2339@flattermodem.net",
        "Taya.Ruecker43321@this-collectivisation.name",
        "Felicity_Parisian7387@salve-cesspool.net",
        "Benjamin.Abshire22136@unawareaccomplishment.org",
        "Dane_Kihn60430@delugestatin.net",
      ],
      "firstName": Array [
        "Rodger",
        "Antwan",
        "Darien",
        "Cleveland",
        "Herta",
        "Maynard",
        "Lisa",
        "Kyla",
        "Monique",
        "Kenya",
      ],
      "float": Array [
        337688789461.4382,
        44760831937.25003,
        72538517294620.84,
        387722004879.1439,
        25278628104.32749,
        2752843483846.25,
        15966019329611.88,
        47396159410232.76,
        79923472824.6301,
        23026512521.56613,
      ],
      "fullName": Array [
        "Junius Mitchell",
        "Maybell Morar",
        "Phyllis Welch",
        "Bernard Kuvalis",
        "Zackery Kemmer",
        "Dortha Okuneva",
        "Hubert Franecki",
        "Jammie Bergnaum",
        "Collin Wyman",
        "Dayne Ritchie",
      ],
      "hex": Array [
        "1",
        "7",
        "0",
        "1",
        "0",
        "4",
        "5",
        "b",
        "8",
        "d",
      ],
      "int": Array [
        7160713753216129,
        8623714756216519,
        2907664520202416,
        5728929856562785,
        8925207268309328,
        1821974564375044,
        7708818009107637,
        7634997838687995,
        5847863928185272,
        1039041630284941,
      ],
      "ipv4": Array [
        "18.177.160.55",
        "236.18.185.110",
        "245.192.149.168",
        "187.185.220.137",
        "230.91.215.176",
        "71.1.103.75",
        "1.172.160.130",
        "216.198.60.69",
        "86.57.80.187",
        "225.94.69.133",
      ],
      "lastName": Array [
        "Armstrong",
        "Gottlieb",
        "Stark",
        "Watsica",
        "Skiles",
        "Kirlin",
        "Conroy",
        "Blanda",
        "Mayert",
        "Parisian",
      ],
      "mac": Array [
        "72:e7:11:3f:b3:6d",
        "e6:12:9a:97:20:23",
        "ae:c2:89:81:d9:3c",
        "22:61:95:8e:5b:01",
        "42:27:f9:3d:ec:56",
        "eb:6c:2b:56:fe:ff",
        "10:5a:c0:f0:46:82",
        "a5:bd:bb:c9:d1:7e",
        "58:33:aa:51:9a:78",
        "1a:72:ed:69:96:41",
      ],
      "oneOf": Array [
        "red",
        "red",
        "blue",
        "green",
        "green",
        "green",
        "green",
        "blue",
        "green",
        "red",
      ],
      "oneOfString": Array [
        "red",
        "red",
        "blue",
        "green",
        "green",
        "green",
        "green",
        "blue",
        "green",
        "red",
      ],
      "paragraph": Array [
        "Yuta keviyo kayo mokai kinmokime vinako sona. Koha kavina so vikai hysota kevi mumohy. Nina hy koyu sovichikai kinhy hanima. Kokivahy kehycea norae vichino cea mikaiko, kiceami cea tayoyu hy yomake vi.",
        "Na ramirae kenayu niranota kochihycea noyu ravino memo, vamiso mike yumeko yo somu. Hami macea naki kanoyuhy vikaina kairae mayokin. Vishi mu kayokeno yomashino kekoayu sotamo.",
        "Sonima meta namokaina yokiva yoni, muno raekaishiha shi ma yomerae raemo. Viyoni tani shi tako kinkekimo no vichi kaimokai. Misoviso mishi so kaita kisona. Shi kichiko raehakeka noma kin kovimu. Hano hyceavi mu mukinkaki ramu. Vi muvakeko hynakerae yuchi noshira momamu. Ha mena nihyka nakikacea ma, yu raenamikai yoshicea takomi hy ceakekina.",
        "Tachino shihyviva kakekome vameki ko kaicea kea. Manova nichimo hyshi mu namoka na kotakima, ceayo va shikekiso haso kaiko. Kota kohamea ni vimavihy viyuhashi kinkaihyta kiyonicea, vanova shiva cea hakinki vika chima memonacea hy. Viceayuvi kinta noke yu hani kerae cea ra, mo moceachina soraehamu kacea haceayo chimechika vi mekoma. Vanikoa muraeniyu nitamena raena chicea. Ceasoshirae rae mano hasohaki muvano kin na tamuchi, hykerae soramo nivachi cea ceanokin.",
        "Yoyu ke shikemu kamovi muceasora. Raekota sokakino vakevi kairaekake hykekano. Rakemuka keshiko na novi komake. Vakinrae kekin yohaso mo ramiavi mika, vakiceayo vako ceano kai kaiakomi. Hy havishi mashi vavimu nakinko mo. Meyuva mihamukai yuko vinome ha kinkimame tahy. Meyo hy tanoceake muhychi yoramechi me vihyrame kinkichikai, ceaniko kinmu yo rae namikaiha cea me.",
        "Mekinchi ra yuvamu ta kachi vima kokevishi. Niami nanoha mu miyomu nimamiyu. So sonihano kai shiavi keso me raekai, shitakinyu sovike ma nomikohy kainora. Shira ni mame kin nakihy kinakin yokesoni, kinkaima tamu moame kintakeno mo moakinyu. Vachina ceakomeyu mome yu vavi mimevima, vimaceavi yo chiso va niraeshike muvanorae.",
        "Vaceashiso kenome ko mova kivachira kahymevi ceake vianike. Motacea raekakiyo nanitake kairahy kinso raekihy kaichihy nonimu. Memova keshi ki raekayo vakina ni, no memasorae shi nonika hymechi.",
        "Shina hamema vamu naceanichi hamova maki kokamu. Haki chirako vi kinchikai mimoma mikohayo mimeyu. Hy vayuvino chikemoha koki kemacea chi sokaimu hamechiyu. Nacea hymehymi hamehy kota nikai, yovi yumimea rae chivamu naso mevani noraekin shimomu.",
        "Hykin muyo makinani kami meraeshi mi kaiva rae, viceake na chike raemiha mohy yuhyvi. Kamesome me chishiha yua mo momi mihamora moviyo. Cea yu yoa so tahykairae, yo hyhake sota chihy mihahyva nimomurae. Mime muchiyohy mo ramoname shisovi kaso ni, ki kechi tayo kinchimoa viha meyohyka nicea.",
        "No viha komekiva somucea kakinmura, kintaviko so moamu kaceachihy kinyo kevake kovameso yu. Cea nokakina yokaira nahy nacea misocea. Tavina nime kinkeha mokivaki kin manishimu. Kai rahykocea yohake kesohyshi minomuna haki yovame, makochita monimo cea kekaicea mihyra yo raemorako. Va masokeno ki vinakinyo mora, meyuva raehy mekiva kimayota nano viakimu.",
      ],
      "password": Array [
        "6p]A}CHVCHm^%[",
        "uhncmK$yLRK$Rz",
        "xDERz2^UF@k&0l",
        "zU!}!pfUL0P0",
        "Mgc2fLib%GLs",
        "gt}u[f^MW^*TY",
        "LCG9{5FG7!#$d",
        "O$BpSel@^*$U",
        "5WsMoee%zx}hR",
        "]^0*vjx\${!5*lN",
      ],
      "phoneNumber": Array [
        "+480151318113415",
        "+96456847771534",
        "+47889504894138",
        "+319332555604",
        "+58999416779275",
        "+0833879449114",
        "+912372016867188",
        "+647553573338",
        "+6743829974869",
        "+6394449799393",
      ],
      "postalAddress": Array [
        "773 Titus Santa Rosa, Dallas 2397, Oman",
        "208 Jerde Rock Hill, Quincy 7127, Chad",
        "814 Goyette Lynchburg, Frederick 5378, Samoa",
        "50 Abbott Sheboygan, Palmdale 8590, Kenya",
        "215 Laisha Gardena, Belleville 5206, Indonesia",
        "464 Allen Dothan, Schaumburg 3604, Iran",
        "119 Rogahn Warren, Carolina 6947, Kyrgyz Republic",
        "367 Hodkiewicz Orland Park, Castro Valley 2456, Bonaire, Sint Eustatius and Saba",
        "654 Maureen Grand Island, Biloxi 4501, Guernsey",
        "525 Garfield Lakeland, Sierra Vista 2770, Bangladesh",
      ],
      "scramble": Array [
        "Tpiscs Ixzmecnq",
        "Dhczqzt Qoswm",
        "Zquuhrz Wjlqr",
        "Hoenhvd Hwaprvk",
        "Mhwyelu Zfvpph",
        "Pvucot Vaczxbr",
        "Pklocp Wisxqaqn",
        "Kbddys Parftrtk",
        "Sgjgho Wwmcx",
        "Hvosd Zktrfes",
      ],
      "sentence": Array [
        "Yuvakin mino moyuhacea kaiyu novi raceamiko mi meni.",
        "No kokayumo kinkaniyo maceahy vi.",
        "Shinota ki hytamu keyunome chiraso yoceamuso ramomi, mekinhy koniravi ta hasomichi shikoyu ki komi.",
        "Me kairaema tamira ni sota, kirae moyu ninachiva yuchiko chiha ki.",
        "Vi shihashimo mimashihy ha ceamu kinchi mashike.",
        "Mukeyoa soshi kaso nihyvakin ceako hykamo.",
        "Koyu kaiceakin chike mo tavicea.",
        "Memuna ceanitacea kaivaki maso yoake me mokayuvi, kinmachirae kaikohyme namunoa yu kota chimeki.",
        "Tako ko nanochino cea mikaso miva.",
        "Mokiyu kai raema mora kanikame yoshiyome momuyomi mitayo, kinkechi koka shi ni memovi kayoniva ramomishi.",
      ],
      "someOf": Array [
        Array [],
        Array [],
        Array [],
        Array [],
        Array [],
        Array [],
        Array [],
        Array [],
        Array [],
        Array [],
      ],
      "streetAddress": Array [
        "88 MacGyver Stillwater",
        "195 Schaden Perris",
        "73 Felicita Atascocita",
        "564 Stehr Janesville",
        "307 Marcelino Sayreville",
        "599 Jacobs Bethesda",
        "86 Kian Catalina Foothills",
        "326 Gislason Pocatello",
        "782 Grady Littleton",
        "906 Mills Aloha",
      ],
      "streetName": Array [
        "Adolph Rancho Cordova",
        "Kuvalis Lubbock",
        "Mitchell Milpitas",
        "Bernie Lake Elsinore",
        "Wolf Hattiesburg",
        "Braxton Lehigh Acres",
        "Skiles Bartlett",
        "Adriana Fairfield",
        "Stoltenberg Fountain Valley",
        "Doris Jurupa Valley",
      ],
      "times": Array [
        Array [
          "Yuka",
          "Somime",
          "Mamevichi",
          "Sokachikai",
        ],
        Array [
          "Maso",
          "Mokamemi",
          "Chikoceami",
          "Moshi",
        ],
        Array [
          "Mira",
          "Raenikai",
          "Yomutami",
          "Noshi",
          "Kinvisova",
        ],
        Array [
          "Vikainoa",
          "Mima",
          "Koviva",
          "Kaki",
        ],
        Array [
          "Kinmomucea",
          "Mohy",
          "Mona",
          "Shimahyme",
        ],
        Array [
          "Muno",
          "Mame",
          "Vaviraeyo",
          "Muracea",
        ],
        Array [
          "Ceachirae",
          "Kaima",
          "Chiko",
          "Rashivacea",
        ],
        Array [
          "Yuna",
          "Hyme",
          "Kinhacea",
          "Nihame",
          "Shimotayo",
        ],
        Array [
          "Hayo",
          "Mora",
          "Tamoke",
          "Mishikai",
        ],
        Array [
          "Nahy",
          "Yoke",
          "Kinkeviyo",
          "Rachi",
          "Muna",
        ],
      ],
      "timezone": Array [
        "America/Nassau",
        "America/Anguilla",
        "America/Dawson",
        "Asia/Qostanay",
        "America/Port_of_Spain",
        "Asia/Riyadh",
        "Atlantic/St_Helena",
        "America/Bogota",
        "Asia/Bangkok",
        "America/Inuvik",
      ],
      "userAgent": Array [
        "Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/534.0.0 (KHTML, like Gecko) Chrome/4029.7553.1270.0 Safari/534.0.0",
        "Mozilla/5.0 (Windows; U; Windows NT 6.0) AppleWebKit/533.1.1 (KHTML, like Gecko) Chrome/1869.7280.9450.0 Safari/533.1.1",
        "Mozilla/5.0 (Macintosh; U; PPC Mac OS X 10_5_3 rv:2.0; RO) AppleWebKit/538.0.2 (KHTML, like Gecko) Version/6841.8822.4566 Safari/538.0.2",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10.8; rv:9.7) Gecko/20100101 Firefox/3648.2318.2409",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_0 rv:2.0; MS) AppleWebKit/535.0.2 (KHTML, like Gecko) Version/4687.1688.6673 Safari/535.0.2",
        "Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 5.2; Trident/6.0; .NET CLR 1.8.33152.0) Version/8144.1032.1101",
        "Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/538.0.2 (KHTML, like Gecko) Chrome/179.4696.6083.0 Safari/538.0.2",
        "Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/538.1.1 (KHTML, like Gecko) Chrome/3748.1533.2936.0 Safari/538.1.1",
        "Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/534.1.1 (KHTML, like Gecko) Chrome/13.8112.2038.0 Safari/534.1.1",
        "Mozilla/5.0 (Windows; U; Windows NT 6.2) AppleWebKit/531.1.1 (KHTML, like Gecko) Chrome/6118.2360.8098.0 Safari/531.1.1",
      ],
      "username": Array [
        "snuffling.greatgrandfather21346",
        "rich.trinket93767",
        "weepy.dip50272",
        "pointless.appetite587",
        "tragic.spec85426",
        "gregarious.vice2339",
        "concur.decision43321",
        "conciliate-hosiery7387",
        "enchant_spool22136",
        "Dane_Kihn60430",
      ],
      "uuid": Array [
        "bf77f3f3-3419-52ef-9354-55f20a169c25",
        "8712a510-02d2-5579-a73a-72373fa4e846",
        "22d47378-a85d-5d75-a3a8-86cb61eb3a0e",
        "e7da5e07-a7fe-5dac-91ab-6b0f529430c5",
        "7fe30a2c-40b1-5492-abe2-3e6fce736dad",
        "1074f696-7128-5378-a2b8-e747c0940ea0",
        "a225b74f-d2c9-5afe-81b6-b9908b36aa36",
        "e11f16ce-3f06-56b6-862f-9b68a20cc735",
        "cc963b7e-a353-588f-825a-279190b206d3",
        "8c766997-b4d2-500c-8d22-e007954d571e",
      ],
      "word": Array [
        "Nohayu",
        "Ceameko",
        "Raenachi",
        "Yoshikova",
        "Kinva",
        "Hymashi",
        "Makoke",
        "Komi",
        "Soa",
        "Kotayo",
      ],
      "words": Array [
        "Monikeko yohyha sonirae",
        "Yokihyme shicea sohameni",
        "Kakin mino",
        "Sovichi raeni raemirako",
        "Ceamo soha",
        "Mikamukin kachimo",
        "Nake kekona kinkaima",
        "Koka yumako nivakeni",
        "Yoracea takeyo",
        "Vashimo mokinhamo mashira",
      ],
    }
  `)
})
