import { TRANSFORMATIONS, NUM_CHECKS } from './testutils'

test('determinism', () => {
  const input = 'some-value'

  const check = (name: string) => {
    const value1 = TRANSFORMATIONS[name](input)

    let i = -1

    while (++i < NUM_CHECKS) {
      expect(TRANSFORMATIONS[name](input)).toEqual(value1)
    }
  }

  Object.keys(TRANSFORMATIONS).forEach(check)
})

test('generated values', () => {
  const count = 10
  const results = {}

  const addResults = (name: string) => {
    const valueResults: unknown[] = []

    let i = -1

    while (++i < count) {
      valueResults.push(TRANSFORMATIONS[name](i))
    }

    results[name] = valueResults
  }

  Object.keys(TRANSFORMATIONS).forEach(addResults)

  expect(results).toMatchInlineSnapshot(`
    Object {
      "bool": Array [
        true,
        true,
        true,
        false,
        true,
        true,
        true,
        false,
        false,
        false,
      ],
      "char": Array [
        "N",
        "v",
        "L",
        "c",
        "L",
        "z",
        "H",
        "C",
        "a",
        "o",
      ],
      "city": Array [
        "New Rochelle",
        "Fountainebleau",
        "Rochester",
        "Berwyn",
        "Norwalk",
        "Toms River",
        "Edinburg",
        "Gary",
        "Ann Arbor",
        "St. Cloud",
      ],
      "country": Array [
        "Singapore",
        "Bouvet Island (Bouvetoya)",
        "El Salvador",
        "Indonesia",
        "Australia",
        "Heard Island and McDonald Islands",
        "Macao",
        "Turkmenistan",
        "Austria",
        "Cote d'Ivoire",
      ],
      "countryCode": Array [
        "NE",
        "GP",
        "GA",
        "SL",
        "BR",
        "DO",
        "RO",
        "NE",
        "BD",
        "BY",
      ],
      "dateString": Array [
        "2011-04-08T15:58:07.000Z",
        "2015-04-12T03:29:46.000Z",
        "1997-02-26T01:45:28.000Z",
        "2006-03-19T02:33:46.000Z",
        "1995-08-16T08:07:37.000Z",
        "1987-08-28T07:22:30.000Z",
        "2001-10-26T21:27:29.000Z",
        "1990-07-07T18:36:31.000Z",
        "1988-05-17T16:28:30.000Z",
        "1982-07-15T18:51:41.000Z",
      ],
      "digit": Array [
        "1",
        "5",
        "7",
        "6",
        "5",
        "7",
        "1",
        "0",
        "8",
        "2",
      ],
      "email": Array [
        "Adell_McDermott59783@fall-secretion.com",
        "Alexandre_Beatty63823@criticalprizefight.info",
        "Mallory.Friesen7259@excitable-citron.net",
        "Vivien_Smith67261@bleedinfection.biz",
        "Finn_Kohler89208@demist-dancing.info",
        "Virginie.Koss58487@hybridisegastropod.net",
        "Sydni.Heller58915@rusty-iceberg.com",
        "Lorenz.Romaguera95818@regurgitate-buffet.net",
        "Gilberto_Metz51009@remoteschizophrenic.name",
        "Jose.Schultz98327@kaleidoscopicbullfighter.info",
      ],
      "firstName": Array [
        "Myrtice",
        "Tre",
        "Blake",
        "Glen",
        "Maverick",
        "Telly",
        "Hester",
        "Jedidiah",
        "Jacinto",
        "Annamae",
      ],
      "float": Array [
        43058934216981.32,
        29148114892700.15,
        16754373201434.24,
        679443988346.876,
        76564149036.984,
        239232035605.5573,
        301000725693.2813,
        23834585777.27076,
        2437072866585.327,
        35969765534601.19,
      ],
      "fullName": Array [
        "Jamaal Leannon",
        "Buddy Jones",
        "Sarai Wisoky",
        "Brown Von",
        "Deshaun McClure",
        "Roberto Thiel",
        "Gaylord Lemke",
        "Rupert Schneider",
        "Jovani Rutherford",
        "Alan Ward",
      ],
      "hex": Array [
        "f",
        "b",
        "9",
        "2",
        "f",
        "f",
        "5",
        "a",
        "8",
        "a",
      ],
      "int": Array [
        2233012514617311,
        2498027555173035,
        717634750782457,
        2823764714090786,
        1357847971058335,
        3604718528088607,
        1453495752300981,
        400948313425050,
        3313229624402728,
        3907585714013562,
      ],
      "ipv4": Array [
        "143.250.111.39",
        "84.61.205.190",
        "223.58.48.191",
        "133.153.159.181",
        "134.55.147.163",
        "118.245.112.153",
        "130.50.103.116",
        "106.193.244.192",
        "128.204.243.119",
        "178.243.100.42",
      ],
      "lastName": Array [
        "O'Conner",
        "Padberg",
        "Hermann",
        "Pfannerstill",
        "Connelly",
        "Batz",
        "Miller",
        "Russel",
        "Steuber",
        "Medhurst",
      ],
      "mac": Array [
        "d4:e5:41:99:5e:cc",
        "9e:b6:1f:56:10:ab",
        "ed:70:ce:f7:98:4c",
        "8a:07:99:0e:3c:8b",
        "3f:a1:e8:17:d7:80",
        "2c:29:d6:6a:54:57",
        "e7:29:62:33:37:ab",
        "62:26:8c:dd:be:99",
        "2d:94:5a:2e:b0:00",
        "69:7e:de:10:48:c1",
      ],
      "oneOf": Array [
        "blue",
        "blue",
        "red",
        "green",
        "red",
        "red",
        "blue",
        "blue",
        "red",
        "blue",
      ],
      "paragraph": Array [
        "Mea tachinacea vakomake nohyva me muraenira, mumota tashiso raeki nomurae ta kovame nihychi ma. Nitaki no rae mo ceasokemu. Ke meraehyni hamime raeshichi chi. Mamoraeha machirae me yohyvira mova yorami. Keshiko vavike cea hymevi na taceakinshi, hyke momema shiyo sohy ko nokaira.",
        "Yuka rayomia koviyuko yokeshi miko. Vi kaishitake ka mochi yuke hynoceaki mumevame keko, kaishi viraetamo rakota ha kin vahymechi. Mokeyu sotachi yoniraeki chitaso ma kake mukaino, yunokamo ceahy nohake chimemi ceaki yova shime. Munoaki noaki vime na kirae na raemi.",
        "Raesoke no mikai mo ceamuha ha yuano. Me vaceachia ko raenokinyo mivashi kiyuniha, mihymimu ra rakeyo kaceamo sokin ni yuchimu raevivaso. Hamohy keso ki ceamiso kaichihy, yomimuki ka shi ceamura kairae ni. Niraenira hamoraso va namemi yonayoni kaimuhy ramoni kinha. Vakichi va mikevahy kocea memikaika kai vime kiraea. Mu vahy soceami mehy ha, hakoshia komemochi kairaenoki moka mu muraetako shichi chi.",
        "Vamotame keko ni chikoshi kaicea kai shichisorae, ceachimuka keraemi keso va tasova ta kiraevame kiha. Raemohy shi vi somi somekorae mehayo. Mi vakiyo raera metamina chi mima ramukemo ha. Haceayova noka vamoyu ko hyshi nikavi haki. Koyu va shiakita moki yokai vi.",
        "Kinmohyke noma takinvake take ra machiraeni, kinmorae shimenichi cea ha vinania mo rameso. Minaso naso hamumino kashi yu, ke vahy mi kahyka kechi kishike. Va chirame mo shimoka rachirahy yo minohyrae yomurae, no nova shi hanimo ka. Vi kemuyo vano ni via ramuhyna kamikaiko shi.",
        "Moke rae mahy me kinohako ta nacea, kimokino mekinma koke ra rame vichicea. Kehyma kinacea mo kivayu ko, kinma vimasoni vasohy kea kikai ko kovikochi. Konimo miyu nakekin hykairae mokai yo hayume. Soma muhamoshi ma yoviyo ceayovi mokinhake. Kinyo kiraeso koki kinso yovayota, kamemi mokachi hamoki mo ramiva ceakicea chiyu. Cea chisoma vihy metahychi nakemu shianime nikema me.",
        "Kaimu nome mo yorayona miravi ta mayohy ha. Raeko kinmime ka nomiraea niso nimeyo ra misomeyo. Tachike ke kamura mi rashitako. Kemoshi soni kokai nochimachi mamo takehy meha kinami, nimo chimo nokinvikai nayuki yura. Kaceamu munamochi hyceanokin hamonashi kai nitamo.",
        "Raeha kayovi ceahychirae cea ravirae morame. Chiyo ha vihayo shi kotaso vika nohanino yuta, haki ma soni soraeta namunishi nokeki hyme. Ma yuhynochi tako kamenomu so, kihy yukinva nakekomi vasomea konahy yumi vahykiyo keyoha. Kerakomi vikoraekin kerame nikaivami kisoha.",
        "Tamohy ka soma komahy yu. Nakin ni meayomi nomu vayusova kinchi. Mina kikeyo sokai hymavia ceakinmihy virahymo, nahyma merayuso rae kinmevi mu. Shiasoa yo vakia mina miranora cea ramo va, ta kinyumota vamu kinso tachiacea no. Shikai kainomiko kaichi ta koceamema menomia ceani yuma. Hachikai hychita vanivachi yoke nonaceavi. Mu kinrakinshi kaia raviva ki.",
        "Monayu vika mokaiso mi vako shichi. Raekaimoha vakoaso kovanichi merae vachiva kimakeva vakinmi, nokikema kaiko no shinashi mohavi raeso vi kimo. Kaishiva sona hy rae vivayoha vakonacea mechishi, ceashi kake mokeka kaiyu kamurae. Machimuko hymimuva ta kavihymo muha, hy sokekin nikako nicea ceamehakin ha. Mikamo ka kaiko kinrame vamu konami yu, kaiko na mohamo ceavinokin tasomemi kaikame. Mi yurami kesoyume chi moke sorashiva namu ceavi.",
      ],
      "password": Array [
        "og&D%MNzUnX8z",
        "h]ha^j1uj^0ZH",
        "JV9&7zI64w#$}^",
        "Og7@&!6F@9o^",
        "vD6K^Yi#gnA1j",
        "sIXLAKQ%omt[0v",
        "QeG}3MOieCBK",
        "]ocDf!bifNkG%Z",
        "yUSXZ[RWLDw6O",
        "kT3JVL*JxWU3w",
      ],
      "phoneNumber": Array [
        "+141390450146694",
        "+66300414399794",
        "+5448474544554",
        "+2526496275317",
        "+24986929025674",
        "+7405282726039",
        "+900282102652161",
        "+3269886033569",
        "+7541233378537",
        "+258465310467186",
      ],
      "postalAddress": Array [
        "168 Kirlin Fields, Fountainebleau 1627, Uganda",
        "917 Quinton Mountains, North Lauderdale 1437, Djibouti",
        "495 Hermiston Plain, Lawrence 4921, United States of America",
        "462 Davis Meadows, Poinciana 2486, Croatia",
        "101 Kunze Union, Millcreek 7549, Cook Islands",
        "22 Gaylord Mountains, Merced 2823, Bangladesh",
        "528 Adella Fort, Westminster 5178, Bouvet Island (Bouvetoya)",
        "589 Pearl Pines, Lincoln 6957, Bosnia and Herzegovina",
        "672 Grady Knolls, Melbourne 7245, Sweden",
        "223 Grady Islands, Albuquerque 9230, Ecuador",
      ],
      "scramble": Array [
        "Oaudnv Newxvjb",
        "Iteqt Quvaw",
        "Zfyrq Trnqed",
        "Iarfh Mrn",
        "Nyhnust TyZwkcc",
        "Gpetjci Ouqoy",
        "Jmvzjpa Dbvpx",
        "Iqejok Lchznyulb",
        "Exqnam Qwxoxcnbcg",
        "Fycu Mqaz",
      ],
      "sentence": Array [
        "Kaitahy viraceaso nikai moshichishi ha naceamuno mevaso hymunikai.",
        "Vashi shi raeko kenameyu shime hyravi raeno.",
        "Yuma yoamiso ramemiso ko nano kinraki kaima.",
        "Hyrae kihychike ko kohakiso tamo, ra kemikehy ceayu nimashina na konanoshi.",
        "Yumacea nomano kaitani yuniko muramuni vavi makinami.",
        "Mi kahyvi vashiso yu raevaviso mucea.",
        "Moketa meyua menaniyo shina kinvaso menikami.",
        "Raehyka ta namo taceashirae me, ceamemimu kema raetakeni niake raehynomu kin ceaviyo mevimo.",
        "Ke ceayuvani ha nika ramiko ra menoha, hahy yukoyuni tahy kinkaina raekai.",
        "Ceayu kaihanova nasokavi nokaimu ceamua vikekani ra, ceaki ka takiraevi na munokai hyma ke.",
      ],
      "someOf": Array [
        Array [
          "paper",
        ],
        Array [
          "paper",
        ],
        Array [
          "paper",
        ],
        Array [
          "rock",
          "scissors",
        ],
        Array [
          "paper",
        ],
        Array [
          "rock",
        ],
        Array [
          "rock",
        ],
        Array [
          "scissors",
          "paper",
        ],
        Array [
          "paper",
          "rock",
        ],
        Array [
          "rock",
          "paper",
        ],
      ],
      "streetAddress": Array [
        "726 Melvina Landing",
        "138 Volkman Plains",
        "697 Bode Lodge",
        "605 Cleo Port",
        "573 Willy Mills",
        "676 Hyman Wall",
        "863 Hand Canyon",
        "577 Crona Point",
        "426 Providenci Harbor",
        "666 Bayer Field",
      ],
      "streetName": Array [
        "Wava Square",
        "Ashton Brooks",
        "Friesen Common",
        "Carson Roads",
        "Coralie Meadows",
        "Jast Islands",
        "Hintz Turnpike",
        "Sipes Freeway",
        "Percy Ports",
        "Macejkovic Plaza",
      ],
      "times": Array [
        Array [
          "Kishi",
          "Ceame",
          "Kimakin",
          "Moramo",
          "Vakerako",
        ],
        Array [
          "Vanorayu",
          "Kairaevayo",
          "Mikaikema",
          "Vimu",
          "Hyke",
        ],
        Array [
          "Ravikai",
          "Vake",
          "Kaishiha",
          "Hyso",
          "Kami",
        ],
        Array [
          "Minoamu",
          "Tayu",
          "Somishi",
          "Niha",
        ],
        Array [
          "Shimehy",
          "Makevamo",
          "Meni",
          "Ceashi",
          "Takinvahy",
        ],
        Array [
          "Kainashi",
          "Kinona",
          "Hayo",
          "Yota",
          "Chiceayuva",
        ],
        Array [
          "Ceakinmuva",
          "Yova",
          "Tahymova",
          "Nime",
          "Vimomako",
        ],
        Array [
          "Muchihy",
          "Chiko",
          "Mani",
          "Kaiaso",
        ],
        Array [
          "Chinocea",
          "Noki",
          "Nayo",
          "Yuchino",
        ],
        Array [
          "Kairaevi",
          "Kinhy",
          "Naninamo",
          "Komami",
        ],
      ],
      "timezone": Array [
        "Asia/Irkutsk",
        "Pacific/Honolulu",
        "Europe/Amsterdam",
        "America/Regina",
        "America/New_York",
        "Europe/Skopje",
        "Asia/Kuwait",
        "Africa/Nairobi",
        "America/Los_Angeles",
        "Australia/Sydney",
      ],
      "userAgent": Array [
        "Mozilla/5.0 (Windows; U; Windows NT 6.1) AppleWebKit/537.1.2 (KHTML, like Gecko) Chrome/32.0.880.0 Safari/537.1.2",
        "Mozilla/5.0 (Windows; U; Windows NT 5.0) AppleWebKit/534.2.0 (KHTML, like Gecko) Chrome/15.0.816.0 Safari/534.2.0",
        "Mozilla/5.0 (Windows NT 5.3; rv:12.5) Gecko/20100101 Firefox/12.5.8",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_5_0 rv:2.0; AR) AppleWebKit/534.1.1 (KHTML, like Gecko) Version/4.1.10 Safari/534.1.1",
        "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_6_9)  AppleWebKit/535.1.1 (KHTML, like Gecko) Chrome/13.0.880.0 Safari/535.1.1",
        "Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10_5_1 rv:5.0; ET) AppleWebKit/531.1.0 (KHTML, like Gecko) Version/5.0.5 Safari/531.1.0",
        "Mozilla/5.0 (compatible; MSIE 7.0; Windows NT 5.1; Trident/4.1; .NET CLR 3.1.41661.7)",
        "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 5.1; Trident/5.0; .NET CLR 2.1.57674.0)",
        "Mozilla/5.0 (X11; Linux x86_64 AppleWebKit/537.0.1 (KHTML, like Gecko) Chrome/33.0.814.0 Safari/537.0.1",
        "Mozilla/5.0 (Windows NT 6.2; Trident/7.0; rv:11.0) like Gecko",
      ],
      "username": Array [
        "sentimental_thrift59783",
        "intent.rainstorm63823",
        "head.hate7259",
        "Vivien.Smith67261",
        "frayed_toilet89208",
        "disafforest-parallelogram58487",
        "Sydni-Heller58915",
        "short-dinosaur95818",
        "equatorial.map51009",
        "enlightened-clinic98327",
      ],
      "uuid": Array [
        "fa006777-5561-5757-9cfc-932f4fc195f3",
        "a741dbac-9c9d-5f10-8169-0e8ffa95230b",
        "1a2f5ec0-7634-5fd6-9a7c-bfc0c80d1c53",
        "d0cb2cf5-e74a-5b02-a71b-a586c66ced70",
        "51253902-61bd-541d-a953-aed16cea071b",
        "039ccb1b-8ef3-5c6e-8b19-b75119783b16",
        "5aa0085e-b1f5-5d52-a427-593de5490276",
        "7e78cb07-6855-5be1-bc39-d58b49392b7f",
        "cbbb383b-b915-5d34-afeb-5d7f9a2d0e61",
        "d720a104-04df-5505-a086-50e3c53306dc",
      ],
      "word": Array [
        "Rashiyo",
        "Shichita",
        "Tamichiva",
        "Ceani",
        "Viceachika",
        "Kinsokinma",
        "Menahy",
        "Masoma",
        "Ceachimuso",
        "Soshima",
      ],
      "words": Array [
        "Vimuhykin tachika kita",
        "Vivako shirahy yoavi",
        "Sovi kaike nihy",
        "Mumiceashi kaichika",
        "Tamime ceako mami",
        "Motashiyu kaike mokaiyuvi",
        "Namu makimea naso",
        "Mukemuki visokinyo",
        "Nanina meamimo",
        "Ceahy vakisona",
      ],
    }
  `)
})
